Update rising_a16

diff --git a/rising_a16 b/rising_a16
--- a/rising_a16
+++ b/rising_a16
@@ -12,9 +12,10 @@ rm -rf out/target/product/*/system/etc/Changelog.txt \
 repo init -u https://github.com/RisingOS-Revived/android -b sixteen-qpr2 --depth=1 --git-lfs --no-clone-bundle
 
 git clone https://github.com/Xtrakari/local_manifest_mh2lm.git --depth 1 -b mh2lm-rising16 .repo/local_manifests
-if [ ! 0 == 0 ]
- then   curl -o .repo/local_manifests https://github.com/Xtrakari/local_manifest_mh2lm.git
- fi
+if [ $? -ne 0 ]; then
+  echo "ERROR: failed to clone local manifest"
+  exit 1
+fi
 
 /opt/crave/resync.sh
 
